# Generated by Django 3.1.5 on 2021-01-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
