# Generated by Django 3.1.5 on 2021-01-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210111_0432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajes',
            options={'ordering': ['time_send']},
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/image/girl.jpeg', upload_to=None),
        ),
    ]
